### ISSUE TITLE
Windows7 BGAPIBackend, ValueError: Cannot configure port.

### ISSUE THREAD

**Issue by designingSparks** [peplin/pygatt#100]
I have installed pygatt and the driver for my BLED112-v1 USB dongle from Bluegiga. The driver is Bluegiga 5.1.2600.0. The device shows up in the device manager as Bluegiga Bluetooth Low Energy (COM29). It's settings are configured by default to

- 9600bps
- 8 data bits
- 1 stop bit

If I do the following:
import pygatt
adapter = pygatt.BGAPIBackend(serial_port='COM29') #without serial_port specified, an error is thrown
adapter.start()

The following error occurs:
ValueError: Cannot configure port, some setting was wrong. Original message: WindowsError(2, 'The system cannot find the file specified.') Changing the baud rate to 115200 doesn't seem to change things.

What could the problem be?

**Comment by peplin** [comment]
Could you try connecting to the serial port with the underlying library we use, `pyserial`? That might help isolate the problem.

Grabbing one of the [pyserial exampes](http://pyserial.readthedocs.io/en/latest/shortintro.html):

```
>>> ser = serial.Serial('COM29', 9600)
>>> s = ser.read(100) 
```

**Comment by designingSparks** [comment]
I was able to fix this by renaming the com port number in the driver to a value under 10.

**Comment by peplin** [comment]
> driver to a value under 10.

Very interesting - I'll mention that in a new troubleshooting section in the README.
