### ISSUE TITLE
Windows 10 BGAPIBackend, Errors on char_write and char_read

### ISSUE THREAD

**Issue by michelMW** [peplin/pygatt#102]
I'm using pygatt with a BLED112 using python 3.6 on Windows 10. I'm using the development version from github, because the pypi version still has the termios issue.

I'm able to connect, scan, discover characteristics and receive data by subscribing to a readable characteristic.

When I try to `char_write` to a writable characteristic, I get `Application error codes`:
```python
device.char_write('6e400004-b5a3-f393-e0a9-e50e24dcca9e', bytearray(b'test'))
```
When I try to `char_read` from a readable characteristic, I get `Unable to read characteristic`:
```python
value = device.char_read('6e400003-b5a3-f393-e0a9-e50e24dcca9e')
```
I'm using the code from the example in the `README` with the logging and everything works except the above lines. Calling `char_write_handle` and `char_read_handle` directly with the appropriate handles fails as well.

I'm I doing something wrong?

**Comment by peplin** [comment]
@michelMW can you share the full debug log from when this happens? At a glance, this looks fine, so there may be something device or Windows specific going on.
