### ISSUE TITLE
Windows 7 error in reset() in gatttool.py

### ISSUE THREAD

**Issue by designingSparks** [peplin/pygatt#109]
I'm using the development version of pygatt from github. When running the example code in basic_bluez_gatttool_sample.py, there is an error when adapter.start() is called. I have traced this to the following line in gatttool.py. The offending line is:
`subprocess.Popen(["sudo", "systemctl", "restart", "bluetooth"]).wait()`

Clearly this command is not supported on Windows.

**Comment by peplin** [comment]
Hey there - unfortunately, BlueZ (where gatttool comes from) [only works on Linux](https://github.com/peplin/pygatt#pygatt---python-module-for-bluetooth-le-generic-attribute-profile-gatt). - if you want to use pygatt you'll need to use a BLE dongle that's compatible with the BGAPI backend instead.

**Comment by GH0st3rs** [comment]
I'm use Gentoo with OpenRC and I have the similar problem!
Why you didn't check `systemctl` or `openrc` ?
