### ISSUE TITLE
Windows error due to use of pexpect in gatttool.py

### ISSUE THREAD

**Issue by designingSparks** [peplin/pygatt#110]
I'm using the development version of pygatt. In in the function start() on line 245 of gattyool.py, pexpect is used to run a command as follows:
`self._con = pexpect.spawn(gatttool_cmd, logfile=self._gatttool_logfile) `

pexpect does not work well on Windows systems although there is wexpect. See: [the pexpect doc](http://pexpect.readthedocs.io/en/stable/overview.html#windows)
It would be good to have a cross platform solution.

**Comment by designingSparks** [comment]
The fix is relatively simple. On windows, the GATTToolBackend doesn't work. If you attempt to use it as described in basic_bluez_gatttool_sample.py, you will run into the above issue.

Therefore I would suggest two enhancements:

- Meaningful error message if the user attempts to create a GATTToolBackend on Windows.
- A better example, showing how to use the BGAPIBackend on Windows.

**Comment by peplin** [comment]
Unfortunately as you found, BlueZ/gatttool are only for Linux. There is an example of how to use the BGAPI backend (which works on Windows) [in the README](https://github.com/peplin/pygatt#example-use) - be aware that the BGAPI backend requires BGAPI compatible BLE dongles, which aren't the same as those that work with BlueZ.

I will definitely add an error message to save the next person some time! Thanks for the report.
