### ISSUE TITLE
Not able to subscribe to characteristic.

### ISSUE THREAD

**Issue by crobertsbmw** [peplin/pygatt#116]
I am not able to subscribe to a characteristic. I can successfully scan, connect, discover_characteristics & read, but it won't let me subscribe.

```
import pygatt
import logging
#logging.basicConfig()
#logging.getLogger('pygatt').setLevel(logging.DEBUG)
 
adapter = pygatt.BGAPIBackend()

def print_this(h, stuff):
    print(stuff)
 
adapter.start()
devices = adapter.scan()
for device in devices:
    if "custom_device" in device["name"].lower():
        print("found device")
        break
    
device = adapter.connect(device["address"])
chars = device.discover_characteristics() # I get some type of a warning here. "UUID b'ffe1' is of unknown type"
value = device.char_read("00002a05-0000-1000-8000-00805f9b34fb") #this address was found by printing the `chars` array
device.subscribe('00002a05-0000-1000-8000-00805f9b34fb', print_this) #ExpectedResponseTimeout
```

The last line throws an `ExpectedResponseTimeout: Timed out after 1.0000s waiting for [<EventPacketType.attclient_procedure_completed: 17>]`.

However, if I print out `device._callbacks` I can see my callback was added to the set.
`defaultdict(<class 'set'>, {14: {<function print_this at 0x0000020B64F9318>}})`

If I turn on logging then I can see that data is coming in, but it's not calling the `print_this` callback.
```
INFO:pygatt.device:Received notification on handle=0x12, value=0xb'430002800b1ff1e00d6fff0f7cfff'
INFO:pygatt.device:Received notification on handle=0x12, value=0xb'410003500a1ff1d00c6eff0a2b437'
```

I tried this which worked as expected:
```
value = "Hello World"
handle = 14
with device._lock:
    if handle in device._callbacks:
        for callback in device._callbacks[handle]:
            callback(handle, value)

>> Hello World
```

So I am pretty baffled at this point. Any help you can give me would be hugely appreciated.

**Comment by peplin** [comment]
Any luck? Please re-open if this is still a problem.
