### ISSUE TITLE
How to send authentication request to the BLE peripheral using the bgapi backend.

### ISSUE THREAD

**Issue by designingSparks** [peplin/pygatt#124]
It appears to me that if the bgapi backend is used there is no means of initiating an authentication request, which is needed for a passkey based connection. Looking through bgapi.py, I can not see any function that supports this. For example, the connect function has no parameter for the password if the connection is encrypted.

Perhaps I am missing something?

**Comment by peplin** [comment]
PyGATT doesn't support passkey authentication with BLE, but both backends do support "Just Works" pairing (from BLE 4.2). I believe passkey authentication has been [deemed insecure](https://eewiki.net/display/Wireless/A+Basic+Introduction+to+BLE+Security#ABasicIntroductiontoBLESecurity-Passkey) so I don't think PyGatt will ever support it.
