### ISSUE TITLE
immediate disconnect

### ISSUE THREAD

**Issue by uncle4** [peplin/pygatt#126]
I'm using pygatt (3.1.1) on my laptop and am connecting to
a Nordic SoC (nRF52832).

Frequently after establishing a connection (and a connection
is indicated on the Nordic radio I get a Disconnect event. Then the
pygatt connection request times out and throws an exception.

The debug output (and screen shot of wireshark session) are:

>>> dev = adapter.connect(addr, address_type=ty)
INFO:pygatt.backends.gatttool.gatttool:Connecting to CD:EE:E4:3F:94:F6 with timeout=5.0
ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to CD:EE:E4:3F:94:F6 after 5.0 seconds.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pygatt-3.1.1-py2.7.egg/pygatt/backends/gatttool/gatttool.py", line 384, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to CD:EE:E4:3F:94:F6 after 5.0 seconds.
>>> 

![disconnect](https://cloud.githubusercontent.com/assets/27894987/25584853/b1340070-2e65-11e7-8204-eb77340b0e2b.png)

I can't get much diagnostics from the Nordic radio: Only connect/disconnect
event notifications.

This could very well be a Nordic issue and not pygatt: I don't have
any other BLE devices to test with.

**Comment by peplin** [comment]
Sorry, I don't have any insight into why this would be failing - I would suggest trying to connect from another BLE client, like an Android phone. If it still disconnects immediately, the bug is likely on the Nordic side.
