### ISSUE TITLE
Can't get Notifications.

### ISSUE THREAD

**Issue by alicanuzun** [peplin/pygatt#134]
Peplin, thank you for your nice work it is really good work, but there is lack of examples and comments about methods. I am trying to connect to my ble device and collect data with notification event, it is like a gauge and counting some numbers about production. I have read,write,notify characteristics, and in windows uwp and android, it works great. Now I have to write the app for raspberry pi, and my only choice is "pygatt". please create example codes about how to get notification when data changed. At least improve your description's about the related methods.

**Comment by peplin** [comment]
Thanks - and yes, documentation and example are always nice to have. If you successfully used the library with your Raspberry Pi, would you consider submitting a pull request with a few examples?
