### ISSUE TITLE
Rpi Zero W, onboard bluetooth

### ISSUE THREAD

**Issue by otecfura** [peplin/pygatt#136]
Hi,

When Iam using pygatt (GATTToolBackend) on rpi-2 model B with external dongle, everything works fine, but when Iam trying to use same code on raspberry pi zero W (bt on board) Iam gettin (Bluetooth: hci0 command 0x1009 tx timeout) on dmesg and pygatt returns connection timeout 110 and bluetooth went down. (bundled version of bluez 5.43, raspbian stretch lite).
Using gatttool in interactive mode (manually not using pygatt) to get data from BLE devices normally working without errors or crashing bluetooth device.

**Comment by peplin** [comment]
Please check out the "Debugging" section in the README - if you can provide the debug log, it will help identify why PyGATT is failing to maintain a stable connection to your device.
