### ISSUE TITLE
How to pairing with a passkey?

### ISSUE THREAD

**Issue by EddieSyu** [peplin/pygatt#147]
Is it possible to sent a pairing request that include IO Capability、OOB ..information to bond my nordic device?

I'm trying to encrypt my DFU service ,so I use a static passkey , but I can't fond any code about pairing and input passkey.

what can I do ?

very thanks for your help

**Comment by peplin** [comment]
Hi Eddie (better late than never, I hope)! Pygatt doesn't support passkey today. It looks like the BGAPI backend has potential for support, but I don't have any plans for the feature at the moment. A pull request would be most welcome.
