### ISSUE TITLE
How to check if BLE session is active

### ISSUE THREAD

**Issue by JorgePe** [peplin/pygatt#151]
Hi.
First things first: congrats on your excellent work!

I've been using pygattlib for small scripts to talk with BLE devices, mostly related to LEGO MINDSTORMS EV3.
Recently I found a problem with python 3 version of pygattlib, my scripts always segfault when receiving notifications. Someone pointed me to pygatt and I've been using it the last 2 weeks with the new LEGO BOOST device, even ordered a BLED112 to use it in a Windows 10 VM so I finally can write code that my LUG fellows can use.

I've been trying to find in pygatt source a way to check if a BLE session is still working (when using the GATTool backend).

I've found `_con.isalive()` but I think it only reports if the shell process is still running. When I force the device to power off, it still returns True even after a minute.

Is there a proper way?

**Comment by peplin** [comment]
There is no official way in the pygatt API, but the gatttol device has a `self._connected` member you can inspect. #106 also added a GATTTbackend-speciifc option to register a callback to be informed when a device disconnects.

**Comment by JorgePe** [comment]
Thanks!
