### ISSUE TITLE
Is it possible to prevent reset com ports?

### ISSUE THREAD

**Issue by iPsych** [peplin/pygatt#157]
In line with previous thread,
https://github.com/peplin/pygatt/issues/132

Is there any way to prevent pygatt from resetting com ports when starts?
It cause crashes the other application using first Bluegiga dongle, when the latter started earlier.
If the other application started later, pygatt seems block the application to find 2nd Bluegiga dongle.

**Comment by peplin** [comment]
#162 adds a new `reset` argument to the `start()` function for BGAPI. This is avaliable in the 4.0 release on PyPi. Hope this helps!
