### ISSUE TITLE
Exception when hcitool scan result contains invalid characters

### ISSUE THREAD

**Issue by nwareham** [peplin/pygatt#170]
We've been using pygatt to assist with development of embedded BLE devices.  Very useful. Thanks.
However, we've encountered a minor issue with a large impact.  Occasionally an incorrectly configured development device will transmit invalid (non Unicode) data in the 'name' field of the hcitool scan response.
This will break the scan functionality of every device using the pygatt GATTTool backend within range of the rogue device.  A Unicode exception is triggered on this line in the scan() method of the GATTToolBackend class in gatttool.py:
   ` for line in scan.before.decode('utf-8').split('\r\n'):`

The local fix we are applying is to modify the line to be:
    `for line in scan.before.decode('utf-8', 'replace').split('\r\n'):`

Issue raised so it could be included in the official source if desired.

**Comment by peplin** [comment]
Thanks for the report! Landing the fix you suggest now.
