### ISSUE TITLE
The response data bytes in connection status handler are not parsed correctly

### ISSUE THREAD

**Issue by SPLavanya** [peplin/pygatt#171]
Hi,
In Pygatt 3.2.0, in pygatt\backends\bgapi\bglib.py, there is a small correction (highlighted below in bold letters) in parsing the response data bytes.
elif packet_type == EventPacketType.connection_status:
            data = unpack('<BB6BBHHHB', payload[:16])
            address = data[2:8]
            response = {
                'connection_handle': data[0], 'flags': data[1],
                'address': address, 'address_type': data[**8**],
                'conn_interval': data[**9**], 'timeout': data[**10**],
                'latency': data[**11**], 'bonding': data[**12**]
                 }

Thanks!

**Comment by peplin** [comment]
Thanks! I confirmed with the [spec](https://www.silabs.com/documents/login/reference-manuals/Bluetooth_Smart_Software-BLE-1.3-API-RM.pdf). The code is obviously wrong too, since we grab bytes 2-7 as the address, then try to use the same bytes for other fields. Doh!
