### ISSUE TITLE
Timeout too short for discover_characteristics()

### ISSUE THREAD

**Issue by Gra55h0pper** [peplin/pygatt#183]
Am getting the following error (on v3.2.0 with BGAPI backend) when calling discover_characteristics():

> **ExpectedResponseTimeout: Timed out after 10.000000s waiting for [<EventPacketType.attclient_procedure_completed: 17>]**

Changing the timeout to 30s in the 'expect' method call fixed it for me:

        self.expect(EventPacketType.attclient_procedure_completed,
                    timeout=30)

(For reference, my device enumerates a total of 52 characteristics)

**Comment by uilyam** [comment]
Thanks for sharing!  I have been seeing this occur as well and this change seems to have resolved this issue for the time being.

**Comment by kgracki** [comment]
Unfortunately even after changing the timeout value to 40s, I still have the same issue. What's strange, while debugging I can see that all characteristics are read properly (with good handlers) and `subscribe` function is returning without any exceptions. I tried with BGAPI v3.0.0 v.3.1.1 v.3.2.0. Working on Linux Manjaro (on Windows everything works just fine)

**Comment by peplin** [comment]
The timeout was extended in #221, which also changes the characteristics discovery to continue even if the ATT procedure complete message wasn't received. This is testing well for me with a BLED112. Thanks for the report!
