### ISSUE TITLE
Successful Subscribing to LED Matrix GATT Service but no notifications.

### ISSUE THREAD

**Issue by G-Pex** [peplin/pygatt#184]
Hi Peplin, firstly thanks for all your hard work!

I'm having a bit of an issue with the MicroBit led_matrix_state GATT service. I'm able to subscribe according to the debug log however once subscribed it never receives any notifications. I'm able to send a char_read to and read the service no problem but I need it to be running asynchronously as it's running alongside a GUI I've built.

Any suggestions?! Appreciate any pointers you could give me :)

**Comment by m-menon** [comment]
Perhaps you can post some code and explain a bit more in detail. For example in some cases it may require more than just subscribing for notifications - it may also require the respective sensor to be enabled for the readings to get updated.

**Comment by peplin** [comment]
Please give v4.0 a try to see if this was due to some bug in pygatt, but otherwise as @m-menon said some example code would be helpful.
