### ISSUE TITLE
Notifications lost using GATTToolBackend on Raspberry Pi 3 - GATTToolReceiver may be to slow?

### ISSUE THREAD

**Issue by netding** [peplin/pygatt#187]
I want to programm a Lego Boost Move Hub with Python using pygatt. My aim is to have a Python code which runs on a Windows machine using a BlueGiga BLE Dongle. But the same code shall also run on a Raspberry Pi 3 (later Zero W) with the built in BLE adapter (BlueZ) as well as with a BlueGiga BLE Dongle. So, the pygatt library would be ideal to handle the BLE communication.
**The BLE communication  works fine with the BlueGiga dongle on both operating systems Windows 7 and Raspian Linux.** I am running this code from the Idle editor.

```
import pygatt
import logging
from binascii import hexlify
from time import sleep

logging.basicConfig()
logging.getLogger('pygatt').setLevel(logging.DEBUG)

def handle_data(handle, value):
    print('Received data: {} from handle" {}'.format(hexlify(value), handle))

HUB_UUID = '00001624-1212-efde-1623-785feabcd123' # Characteristic for Notifications
HUB_MAC = '00:16:53:AB:64:29' # MAC address of the Move Hub

#Either using BlueGiga external USB adapter or the internal BLE adapter of the Raspberry Pi
#adapter = pygatt.BGAPIBackend() # works fine
adapter = pygatt.GATTToolBackend() # only 3-5 of 9 notifications

try:
    adapter.start()
    sleep(1)
    device = adapter.connect(HUB_MAC)
    sleep(1)
    device.subscribe(HUB_UUID,callback=handle_data)
    print('Wait for callback ...')
    sleep(3)
finally:
    adapter.stop()
```

The source code above returns the nine following notifications (**adapter = pygatt.BGAPIBackend()**) on a Raspberry Pi as well as on a Windows machine:

_Wait for callback ...
Received data: b'0f0004010125000000001000000010' from handle" 14
Received data: b'0f0004020126000000001000000010' from handle" 14
Received data: b'0f0004370127000000001000000010' from handle" 14
Received data: b'0f0004380127000000001000000010' from handle" 14
Received data: b'090004390227003738' from handle" 14
Received data: b'0f0004320117000000001000000010' from handle" 14
Received data: b'0f00043a0128000000001000000002' from handle" 14
Received data: b'0f00043b0115000200000002000000' from handle" 14
Received data: b'0f00043c0114000200000002000000' from handle" 14_

(This data gives a feedback on the peripheral devices connected to the Move Hub.)

However, if the **GATTToolBackend** is used (rest of the python code is not altered), then only four, sometimes three or five notifications appear on a Raspberry Pi (adapter = pygatt.GATTToolBackend(), two successive calls of the same source code, internal BLE adapter of Raspberry Pi):

Wait for callback ...
Received data: b'0f0004010125000000001000000010' from handle" 14
Received data: b'090004390227003738' from handle" 14
Received data: b'0f00043b0115000200000002000000' from handle" 14
Received data: b'0f00043c0114000200000002000000' from handle" 14

Wait for callback ...
Received data: b'0f0004010125000000001000000010' from handle" 14
Received data: b'090004390227003738' from handle" 14
Received data: b'0f0004320117000000001000000010' from handle" 14
Received data: b'0f00043c0114000200000002000000' from handle" 14

Only four notifications are returned. And if I run the code again, sometimes different notifications are returned.

Here is the debug output (this time only three notifications were returned, may be because the GATTTollReceiver is even slower due to the debug code):

_DEBUG:pygatt.backends.gatttool.gatttool:gatttool_cmd=gatttool -i hci0 -I
INFO:pygatt.backends.gatttool.gatttool:Running...
INFO:pygatt.backends.gatttool.gatttool:Connecting to 00:16:53:AB:64:29 with timeout=5.0
DEBUG:pygatt.device:Looking up handle for characteristic 00001624-1212-efde-1623-785feabcd123
DEBUG:pygatt.backends.gatttool.gatttool:Found characteristic 00002a05-0000-1000-8000-00805f9b34fb, value handle: 0x3
DEBUG:pygatt.backends.gatttool.gatttool:Found characteristic 00001624-1212-efde-1623-785feabcd123, value handle: 0xe
DEBUG:pygatt.device:Found <Characteristic uuid=00001624-1212-efde-1623-785feabcd123 handle=14>
DEBUG:pygatt.backends.gatttool.gatttool:Sending cmd=char-write-cmd 0x0f 0100
INFO:pygatt.backends.gatttool.gatttool:Sent cmd=char-write-cmd 0x0f 0100
INFO:pygatt.device:Subscribed to uuid=00001624-1212-efde-1623-785feabcd123
Wait for callback ...
INFO:pygatt.device:Received notification on handle=0xe, value=0xb'0f0004010125000000001000000010'
Received data: b'0f0004010125000000001000000010' from handle" 14
INFO:pygatt.device:Received notification on handle=0xe, value=0xb'090004390227003738'
Received data: b'090004390227003738' from handle" 14
INFO:pygatt.device:Received notification on handle=0xe, value=0xb'0f00043c0114000200000002000000'
Received data: b'0f00043c0114000200000002000000' from handle" 14
INFO:pygatt.backends.gatttool.gatttool:Stopping
INFO:pygatt.backends.gatttool.gatttool:Listener thread finished_

If I activate the the notifications of the same characteristic using **gatttool** on the Raspberry Pi 3 using its internal BLE adapter, I get all nine notifications:

_pi@raspberrypi:~ $ sudo gatttool -b 00:16:53:AB:64:29 -I
[00:16:53:AB:64:29][LE]> connect
Attempting to connect to 00:16:53:AB:64:29
Connection successful
[00:16:53:AB:64:29][LE]> char-write-cmd 0x0f 0100
Notification handle = 0x000e value: 0f 00 04 01 01 25 00 00 00 00 10 00 00 00 10 
Notification handle = 0x000e value: 0f 00 04 02 01 26 00 00 00 00 10 00 00 00 10 
Notification handle = 0x000e value: 0f 00 04 37 01 27 00 00 00 00 10 00 00 00 10 
Notification handle = 0x000e value: 0f 00 04 38 01 27 00 00 00 00 10 00 00 00 10 
Notification handle = 0x000e value: 09 00 04 39 02 27 00 37 38 
Notification handle = 0x000e value: 0f 00 04 32 01 17 00 00 00 00 10 00 00 00 10 
Notification handle = 0x000e value: 0f 00 04 3a 01 28 00 00 00 00 10 00 00 00 02 
Notification handle = 0x000e value: 0f 00 04 3b 01 15 00 02 00 00 00 02 00 00 00 
Notification handle = 0x000e value: 0f 00 04 3c 01 14 00 02 00 00 00 02 00 00 00 
[00:16:53:AB:64:29][LE]>_ 

So, I suspect that the GATTToolReceiver of the pygatt library may be to slow to catch all nine notifications.

Does anybody have an idea to solve this problem? 

Thank you in advance for your answers and many thanks to the authors of the pygatt library.

Best regards

Stefan

**Comment by peplin** [comment]
> So, I suspect that the GATTToolReceiver of the pygatt library may be to slow to catch all nine notifications.

This has been true in the past, because of the way the string parsing was done on the output of gatttool. A few enhancements landed in v4.0 that may make this better. Please give it another try and open a new ticket if you still see a performance different.

That said, gatttool is deprecated and we will be dropping support for it soon, so if you have a BLED112 I would continue using that!
