### ISSUE TITLE
char_write return value not propagated back to caller

### ISSUE THREAD

**Issue by yjlou** [peplin/pygatt#189]
Hi there,

Thanks for developing this handy library. Very appreciated.

We are using char_write() to get the return value of CharacteristicWrite from firmware. However, we noticed that the return value is dropped at the code (https://github.com/peplin/pygatt/blob/master/pygatt/backends/bgapi/device.py#L115).

I am not sure if it is intentional. If not, I can send out a pull-request. How do you think?

Thanks.

**Comment by peplin** [comment]
Thanks for the report. This wasn't for any particular reason, I just didn't have a good means to test it. I would be happy to merge a pull request.
