### ISSUE TITLE
Pygatt does not work on Linux(Debian)

### ISSUE THREAD

**Issue by sszaharovd** [peplin/pygatt#192]
Hi. I installed a library through pip3. I'm using Python 3.6. I copied the code from the example and changed it to my MAC address. As a result, it produces an error when starting:

WARNING: No module named 'pexpect'
Traceback (most recent call last):
  File "/home/bt/venv/lib/python3.6/site-packages/pygatt/backends/bgapi/bgapi.py", line 155, in _open_serial_port
    serial_port = self._serial_port or self._detect_device_port()
  File "/home/bt/venv/lib/python3.6/site-packages/pygatt/backends/bgapi/bgapi.py", line 131, in _detect_device_port
    raise BGAPIError("Unable to auto-detect BLED112 serial port")
pygatt.backends.bgapi.exceptions.BGAPIError: Unable to auto-detect BLED112 serial port

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bt/bt.py", line 8, in <module>
    adapter.start()
  File "/home/bt/venv/lib/python3.6/site-packages/pygatt/backends/bgapi/bgapi.py", line 187, in start
    self._open_serial_port(max_connection_attempts=1)
  File "/home/bt/venv/lib/python3.6/site-packages/pygatt/backends/bgapi/bgapi.py", line 170, in _open_serial_port
    "No BGAPI compatible device detected")
pygatt.exceptions.NotConnectedError: No BGAPI compatible device detected

For example, I create the same connection through a standard utility - a screenshot attached

![selection_001](https://user-images.githubusercontent.com/36671022/40657568-096d31c8-6351-11e8-9c77-79030f866012.png)
![selection_002](https://user-images.githubusercontent.com/36671022/40657571-0d24a06c-6351-11e8-8a6b-157909223703.png)

How can I solve this problem?

**Comment by bartkowiaktomasz** [comment]
Hi, @sszaharovd. Have you managed to solve the problem? I keep getting the same error.

**Comment by sszaharovd** [comment]
Yes, I solved this problem by borrowing another class(GATTToolBackend), which I also approached.

**Comment by bartkowiaktomasz** [comment]
@sszaharovd thanks. Do you have something like:

`import pygatt

adapter = pygatt.backends.BGAPIBackend()

try:
    adapter.start()
    device = adapter.connect('FF:3C:8F:22:C9:C8')
    value = device.char_read("2d30c082-f39f-4ce6-923f-3484ea480596")
finally:
    adapter.stop()`

**Comment by bartkowiaktomasz** [comment]
@sszaharovd thanks. Do you have something like:
```
import pygatt

adapter = pygatt.backends.BGAPIBackend()

try:
adapter.start()
device = adapter.connect('FF:3C:8F:22:C9:C8')
value = device.char_read("2d30c082-f39f-4ce6-923f-3484ea480596")
finally:
adapter.stop()
```

**Comment by sszaharovd** [comment]
class BLE:
    def __init__(self):
        self.adapter = pygatt.GATTToolBackend()

    @staticmethod
    def notify(handle, value):
        callback_value = hexlify(value)
        print('Response => ', callback_value)

    def send(self, cmd):
        try:
            self.adapter.start()
            device = self.adapter.connect(DEVICE_MAC)
            device.char_write(WRITE_DATA, bytearray(cmd), wait_for_response=True)
            device.subscribe(READ_DATA, callback=self.notify)
        except Exception as e:
            print('Error: ', format(e))
            pass

        finally:
            self.adapter.stop()


if __name__ == '__main__':
    a = BLE()
    a.send([0x00, 0x00, 0x00....])

**Comment by sszaharovd** [comment]
Use pygatt.GATTToolBackend() - he will give you just what you want

**Comment by bartkowiaktomasz** [comment]
@sszaharovd Thanks for your responses. Unfortunately _pygatt_ each time gave me:
 ```Timed out connecting to [MAC ADDRESS]```
I solved all the problems by using [**_bluepy_**](https://github.com/IanHarvey/bluepy)

**Comment by sszaharovd** [comment]
@bartkowiaktomasz, You can also use the library bluetooth.ble. It also works fine with devices. But in this library I liked the fact that it directly works with functions gatttools, which I had to

**Comment by bartkowiaktomasz** [comment]
@sszaharovd Thanks. I ended up using _pexpect_, which automates gatttool commands directly, therefore resulting in the best speed.

**Comment by zhangzhii** [comment]
Hi,
I solved this problems by using a previous commit of pygatt/backends/bgapi/bgapi.py
[https://github.com/peplin/pygatt/blob/2b6c2e4007be9b63e58d51101bd8aaca46093674/pygatt/backends/bgapi/bgapi.py](url)
and replace the line 506 by:
`for i in range(0, len(field_value) // 16):  # 16 bytes`

I have no idea why the latest version of pygatt doesn't work in my case, neither on Linux nor Windows. 
Hope this will give you what you want.

**Comment by peplin** [comment]
v4.0 (just released) includes a few improvements for setting up connections. I'm not sure what the last BGAPI change is referring to (the link doesn't work anymore), but give the latest version a try. Please open a new issue if there are still problems. Thanks!
