### ISSUE TITLE
Notifications and send_write_handle race error

### ISSUE THREAD

**Issue by Webrow** [peplin/pygatt#198]
We have listeners for notifications on handle 0x020b
While we are sending data to 0x020b the same handle sends a notification back. 
It looks like this:  
> message1-pack1 sending
> message1-pack1 sent
> message1-pack2 sending
> message1-pack2 sent
> message1-pack3 sending
> message1-pack3 sent
> message1-pack4 (last pack) sending
--Note, no sent
> Recv packet 1 notification on handle
> Recv packet 2 notification on handle
> Recv packet 3 notification on handle
> Recv packet 4 notification on handle
> message2-pack1 sending

So message1-pack4 is never sent. 
Is this threaded? Is it locked?

**Comment by peplin** [comment]
Thanks for the report! I believe you did find a race condition.

> Is this threaded? 
Yes

>Is it locked?
Not well enough! We had a lock around sending, but not on the receive thread.

**Comment by peplin** [comment]
FIxed by #228
