### ISSUE TITLE
Indications do not work on 4.0.1

### ISSUE THREAD

**Issue by EricGCooper** [peplin/pygatt#231]
Hello, I just upgraded to 4.0.1 and indication generates the error [here](https://github.com/peplin/pygatt/blob/master/pygatt/backends/gatttool/gatttool.py#L540) 

I downgraded to 3.2.0 and indications do work.

Please let me know if there is more information I can provide.

I am busy for the next month but after that I may be able to be a maintainer.

**Comment by peplin** [comment]
Thanks Eric, I can confirm this is a regression. There is a new regex for parsing notifications (27bfc28774f18ad84c9ee8332e67f03268bcd276) but it doesn't support the `Indication` response from gatttool.
