### ISSUE TITLE
 Windows 10, BGAPIBackend - No characteristic found matching

### ISSUE THREAD

**Issue by vlcmartinez680** [peplin/pygatt#235]
Hello everyone
I try to comunicate with a RN4870 BLE module from Microchip.
The module has an uuid to send (uuid_tx) and another to receive (uuid_rx)
I have tested all posibilities, I try to send, to rend and to subscribe and I get allways the same alert "No characteristic found matching". I could read, write or subscribe those uuids with the smartphone with other app, so I am sure that the uuids exist. 

Could you please check that issue? 

Code: 
```
import pygatt
from binascii import hexlify

mac     =  '34:81:F4:06:DB:B9'
uuid_rx = '49535343-1E4D-4BD9-BA61-23C647249616'
uuid_tx = '49535343-8841-43F4-A8D4-ECBE34729BB3'

adapter = pygatt.BGAPIBackend()

try:
    adapter.start()
    device = adapter.connect(mac)
    device.char_write(uuid_tx, bytearray([45, 11]))
finally:
    adapter.stop()

```
Error: 

![image](https://user-images.githubusercontent.com/35928787/55558443-62b7e400-56ec-11e9-8ef7-930d010c421b.png)

I got at the begging that alert: **UUID b'9bb3**' is of unknown type
it is weird, that the characteritistic is not found, but the last four characters are found

**Comment by peplin** [comment]
Please try updating to a newer version of PyGatt. This should be fixed by #148 - you can find more details about the underlying bug in #140.
