### ISSUE TITLE
[Help] Connecting to more than one device

### ISSUE THREAD

**Issue by marquesn** [peplin/pygatt#238]
I've been trying to connect, read, and write more than one device using threads but it'll only work on one of them.  

If I try to connect a new adapter for every device, it reads the data from one of them and then throws:
`Can't init device hci0: No such device (19)` 
followed by a timeout on connecting to the device.

(Example below) If I try using one adapter for all devices, it reads the data from one of them and then throws:
`NotConnectedError` 
on one of the devices.

Would I have to declare a new adapter for every device? Or does one adapter handle multiple?

Below is just the example of using one adapter for all devices (adapter.start() outside of the loop):
```
adapter = pygatt.GATTToolBackend()

devices = ['30:AE:A4:FE:07:A2',
           '30:AE:A4:FE:0E:56']

readHandles = ["0x0039",
               "0x003b",
               "0x003d"]

def connect_device(address):
    device = adapter.connect(address)
    for i in range(0,len(readHandles)):
        value = device.char_read_handle(readHandles[i])
        print "Value: ", value

if __name__ == "__main__":
    adapter.start()
    for i in range(0,len(devices)):
        connectThread = Thread(target=connect_device, args=(devices[i],))
        connectThread.start()
```

**Comment by kevin-george** [comment]
https://github.com/peplin/pygatt/blob/c650b8e805c8216ba9976323136301f8ab251675/pygatt/backends/gatttool/device.py#L24
