### ISSUE TITLE
reconnecting after connection disabled

### ISSUE THREAD

**Issue by Taha2312** [peplin/pygatt#245]
I would like to extend the following code with the functionality of reconnecting:

import pygatt
import time
adapter = pygatt.GATTToolBackend()
try:
  adapter.start()																
  device =adapter.connect(mac-adress)    
  device.char_write(uuid,bytearray([0x73, 0x74, 0x61, 0x72, 0x74]))
  while(1):
        value = device.char_read(uuid)
        v = value.decode('utf-8')
        print(v)
        time.sleep(1)																
except pygatt.exceptions.NotConnectedError:
    adapter.reconnect(adapter,30)

If the BLE connection is lost for some reason i would like to go for a reconnection try. But I still get NotConnectedError although I put an exception handling code. Can someone help me with this issue? Thank you in advance.

**Comment by PokerMakyo** [comment]
`connnect` method have also `auto_reconnect` parameter. You can set it to True to enable autoreconnect.
