### ISSUE TITLE
Process finished with exit code -1073740940 (0xC0000374)

### ISSUE THREAD

**Issue by riccardobrue** [peplin/pygatt#246]
Hi, I am using your library for a communication with two Bluetooth (LE) devices using GATT. What I need to do is to subscribe for some notifications and store the received data (every 100 ms per device) into a file.
The communication works well in the 95% of the times, I have communicated with the devices for more than 3 hours without any problem, but sometimes (sometimes after 5 minutes, sometimes after hours) I am facing the following error:
--> Process finished with exit code -1073740940 (0xC0000374)

I am not understanding what could cause this error because I have no references, and it may be caused by other application's components, but I have no clue. What I am trying to understand is if this error (that seems to be related to some heap corruption error on Windows) could be raised from your library.

PS: I am developing on Windows using PyCharm community, and the application is using PyQt. I repeat that the error happens only sometimes without any clue.

**Comment by peplin** [comment]
Windows support is "best effort" since I don't regularly have access it it. Unfortunately, I can't offer any advice here.
