### ISSUE TITLE
Distribution rights for the PDFs?

### ISSUE THREAD

**Issue by petterreinholdtsen** [peplin/pygatt#253]
Hi.  As far as I can tell, the copyright terms of both docs/Bluetooth_Core_V4.0.pdf docs/Bluetooth_Smart_Software_v1.3.1_API_Reference.pdf do not grant the right to distribute them.  The default terms in the copyright laws seem to apply, which prohibit anyone except the right holders to distribute the words publicly without explicit approval by right holders.

Did you secure such rights, or is there some other legal framework in place to allow you to distribute these PDFs?

I've been working on Debian packaging, and came across this issue when creating a debian/copyright file describing the copyright terms of the source files.

See also https://bugs.debian.org/939619 .

**Comment by peplin** [comment]
I have no issue removing the PDFs if it poses a problem for packaging. I don't have any exceptions from the Bluetooth standards group, but the specs are freely shared on their website: https://www.bluetooth.com/specifications/archived-specifications/ 

I'll cut a new release with #254 shortly.
