### ISSUE TITLE
Add @functools.wraps to decorators

### ISSUE THREAD

**Issue by minno726** [peplin/pygatt#256]
The `@connection_required` decorator currently overwrites the documentation on all of the functions that use it. For example:

```python
>>> adapter = pygatt.BGAPIBackend()
>>> adapter.start()
>>> device = adapter.connect("90:70:65:FC:E8:6C")
>>> help(device.char_read)
Help on method wrapper in module pygatt.backends.bgapi.device:

wrapper(*args, **kwargs) method of pygatt.backends.bgapi.device.BGAPIBLEDevice instance
```

By adding [`@functools.wraps`](https://docs.python.org/2/library/functools.html#functools.wraps) to the wrapper function defined in `connection_requred`, the docstring and name will be passed through.

**Comment by peplin** [comment]
Good call, thanks. We had this on the gatttool backend but not bgapi for some reason.
