### ISSUE TITLE
Notification stream from Polar H10 runs out 

### ISSUE THREAD

**Issue by HURoeck** [peplin/pygatt#259]
Hi 
I use pygatt from a RPI Zero W to access a Polar H10 chest belt in order to let an LED blink with the heart rate. Discovery, subscription and getting first notifications all work fine, but after roughly 100s no notifications appear anymore. The debug log doesn't give a hint either. Any help would be appreciated!
The used code is:

import pygatt
from pygatt.util import uuid16_to_uuid
from pygatt.exceptions import NotConnectedError, NotificationTimeout
import binascii
#from symbol import argument
import time
import RPi.GPIO as gpio

MAC = 'E7:17:FD:20:B1:AA'   # MAC address of the Polar H10 belt
HR = 0
RRi1 = 0
RRi2 = 0
LED_On_time = 0.15       # seconds
GPIO_port = 19
gpio.setmode(gpio.BCM)
gpio.setup(GPIO_port, gpio.OUT)

"""
@param handle: indicate the handle from a characteristic
@param measure: value received from notification  
"""
def callback(handle, measure):
    global HR, RRi1, RRi2

    if handle == 16:
        for i in range(len(measure)):
            if i == 1:
                print('Heart rate = ',measure[1],' bpm')
                HR = measure[1]
            if i == 2:
                RRi1 = round((measure[2] + 256*measure[3])/1024,2)
                print('RR intervall = %.2f' % RRi1,' s')
            if i == 4:
                RRi2 = round((measure[4] + 256*measure[5])/1024,2)
                print('RR intervall = %.2f' % RRi2,' s')
             
            
def Init():
    
    adapter = pygatt.GATTToolBackend()
    adapter.start()

    try:
        """ connect to bluetooth MAC addres with 5 seconds timeout"""
        device = adapter.connect(MAC, address_type=pygatt.BLEAddressType.random)
#        print('Device: ', device)
        
        """ generate characteristics uuid's  """
        uuid_heart_service = uuid16_to_uuid(0x2A37)
#         uuid_battery_service = uuid16_to_uuid(0x2A19)
#         uuid_set_sensor_location = uuid16_to_uuid(0x2A39)
#         uuid_get_sensor_location = uuid16_to_uuid(0x2A38)
#         
        """ discover all characteristics uuid's"""
        device.discover_characteristics()
        
        """subscribe(self, uuid, callback=None, indication=False):
            
        Enable notifications or indications for a characteristic and register a
        callback function to be called whenever a new value arrives.

        @param: uuid -- UUID as a string of the characteristic to subscribe.
        @param callback -- function to be called when a notification/indication is
                    received on this characteristic.
        @param indication -- use indications (where each notificaiton is ACKd). This is
                    more reliable, but slower. 
        
        """
        
        device.subscribe(uuid_heart_service, callback, False)
#        device.subscribe(uuid_battery_service, callback, False)
        
        """
        To send a message use function char_write(self, uuid, value, wait_for_response=False):
        
        @param uuid - uuid from what service will receive
        @param value - value to send
        @param wait_for_response - if a response from server is expected
        
        e.g
        device.char_write(uuid, value, False)
        """
        
    except NotConnectedError:
        print('No connection established ')
        quit()
        

Init()
t = time.time()    # Initialize with a reasonable value
while(1):
    gpio.output(GPIO_port, gpio.HIGH)
    time.sleep(LED_On_time)
    gpio.output(GPIO_port, gpio.LOW)
    time.sleep(max(0, 60/HR - (time.time() - t)))    
    t = time.time()

**Comment by PokerMakyo** [comment]
Please try to:
sudo rpi-update ce2a9f85a6fd88f8c42ef54b7bad99b42e76e403
You need kernel without this patch:
https://lore.kernel.org/linux-bluetooth/f9176553-d4d5-c2e0-ecd7-937cac0d8098@gmail.com/
