### ISSUE TITLE
No BGAPI compatible device detected on Mac OS 

### ISSUE THREAD

**Issue by linan21** [peplin/pygatt#260]
Hello,

I am trying to connect to my Muse headband by following the instructions on [https://github.com/NeuroTechX/bci-workshop/blob/master/INSTRUCTIONS.md](url). 

Everything worked the first few times I ran the program, now, I get an error. I did not change the code or anything else on my computer. 

When I run the command `python -u muse-lsl.py --name Muse-<NAME>` I get the following error in the terminal: 
Traceback (most recent call last):
  File "muse-lsl.py", line 44, in <module>
    muse.connect()
  File "/Users/home/Desktop/bci-workshop/python/muse/muse.py", line 44, in connect
    self.adapter.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygatt/backends/bgapi/bgapi.py", line 222, in start
    self._open_serial_port()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygatt/backends/bgapi/bgapi.py", line 185, in _open_serial_port
    "No BGAPI compatible device detected")
pygatt.exceptions.NotConnectedError: No BGAPI compatible device detected

The mac version is 10.14.6. I do have a BLED112 dongle plugged in. I have looked through other solutions and tried them, nothing seems to work. When I run `system_profiler SPUSBDataType` the dongle shows up as:   
            
              Product ID: 0x0001
              Vendor ID: 0x2458
              Version: 0.01
              Serial Number: 1
              Speed: Up to 12 Mb/sec
              Manufacturer: Bluegiga
              Location ID: 0x14110000 / 29

I have also tried uninstalling muselsl and pygatt and installing the two again, I still get the same error. 

Could you please tell me how I can fix this? Let me know if you need other information.

**Comment by peplin** [comment]
Sorry, I don't have a Mac to test with.
