### ISSUE TITLE
How to check battery level of bluetooth device ?

### ISSUE THREAD

**Issue by ttpro1995** [peplin/pygatt#265]
I want to check battery level of bluetooth device (headphone, ...). 
When I connect to phone, It can check battery level. 
How to do that with pygatt ? Example code please.

**Comment by askpatrickw** [comment]
You should post this question to [Stackoverflow](https://stackoverflow.com/questions/tagged/bluetooth-lowenergy) and when you do that, include the make model of your device and the code you've tried already.

**Comment by peplin** [comment]
I believe there's a standard or semi-standard BLE characteristic for battery level. Search around and you should be able to find it.
