### ISSUE TITLE
When I use gatttool interactivea and connect to my multimeter, it starts sending notifications, how to do in pygatt?

### ISSUE THREAD

**Issue by niwla23** [peplin/pygatt#267]
I can use the interactive shell of gatttool and connect to my multimeter. It directly starts notifications, but pygatt needs an UUID for that. How can i do it without? Is there some default that gatttool is using?
I have no idea what my UUID is and
`gatttool -i hci0 -b A5:B3:C2:22:0F:EA --primary` returns sic ids but none of them works.

**Comment by Niwla23** [comment]
I am on linux

**Comment by peplin** [comment]
The gatttool backend runs the `gatttool` CLI under the hood, so it shouldn't be doing anything different. Since gatttool is deprecated by BlueZ there's unfortunately not much we can do.
