### ISSUE TITLE
Need an example for receive_notification

### ISSUE THREAD

**Issue by niwla23** [peplin/pygatt#268]
How do I use it?
I tried the following:
device.receive_notification(0x0031, bytes(0100))
device.receive_notification(0x0031, 0100)
device.receive_notification(0x0031, "0100"))

How shall i do it?

**Comment by peplin** [comment]
`receive_notification` is a private internal method, you don't want to be calling that directly. Check out the subscription example in the README. You provide the characteristic UUID and a callback function.
