### ISSUE TITLE
Obtaining corrupted data when using indications

### ISSUE THREAD

**Issue by CLDiego** [peplin/pygatt#273]
Hi, first of all, thanks for the work done so far with this module, it is extremely helpful for testing BLE devices on a PC environment. 

I've been testing pygatt using the gattool backend to test a BLE prototype using the RN4870. 

One of the services that the device has is a transparent UART, thus, I can receive different amounts of data at one time. Subscribing to the characteristic works fine, but when using notifications, I've seen some data losses. I've found that increasing the MTU improves this, but since the data size varies, it hard to define an adequate MTU.

For this reason, I want to use indications, as I understand they should be more reliable. The problem is that after receiving a certain amount of data, I start getting corrupted data with weird symbols. Within that corrupted data, one thing I noticed is that I start getting the name of the device too, leading me to believe that this might be a parsing issue.

I would appreciate any ideas on how to fix this issue. Thanks!

**Comment by peplin** [comment]
If you are able to share a debug log when this happens, I can take a look: https://github.com/peplin/pygatt#debugging
