### ISSUE TITLE
device.subscribe() always return timeout error

### ISSUE THREAD

**Issue by AbhishekEkhare** [peplin/pygatt#279]
Hi,

I am facing two issues with the example codes provided:-

Issue1: _device.subscribe("845ce63c-d003-423c-8922-818676d34255", callback=handle_data)_ always returns the error **pygatt.backends.bgapi.exceptions.ExpectedResponseTimeout: Timed out after 10.000000s waiting for []**

Issue2:- char_read() and char_write() do not work, but char_read_handle() and char_write_handle() work 
i.e. _value = device.char_read_handle(55)_ **<-- works**
_value = device.char_read("845ce63c-d003-423c-8922-818676d34255")_ **<-- does not work**

I am really stuck with these issues and any help is much appreciated!

**Comment by peplin** [comment]
If you are still having an issue, please upload the debug log.
