### ISSUE TITLE
Use with built in bluetooth on macOS?

### ISSUE THREAD

**Issue by niemyjski** [peplin/pygatt#281]
I have a bluetooth LE device that is paired with my MacBook Pro via browser/os. But I cannot get this library to run and detect the same device no matter what I try. To me it seems as if I am required to use a bluetooth dongle from reading all the threads (which is how this library came to be)? What do I need to do to use the built in bluetooth? I've tried a bunch of stuff. 

```
INFO:pygatt.backends.bgapi.bgapi:Initialized new BGAPI backend
INFO:pygatt.backends.bgapi.bgapi:Auto-detecting serial port for BLED112
DEBUG:pygatt.backends.bgapi.util:Found 1 serial USB devices
DEBUG:pygatt.backends.bgapi.util:Checking serial USB device: /dev/cu.Bluetooth-Incoming-Port - n/a
Traceback (most recent call last):
....


pygatt.backends.bgapi.exceptions.BGAPIError: Unable to auto-detect BLED112 serial port
```

Latest stable lib/master on python 3.x running macOS latest.

**Comment by m9h** [comment]
Unfortunately you will need the BLED112 adaptor on Mac OS X. If you have found an alternative solution I would be very interested to know more about it.

**Comment by peplin** [comment]
Sorry, I don't have a Mac and don't know much about its Bluetooth subsystem.
