### ISSUE TITLE
Taking data from two or more devices in real time

### ISSUE THREAD

**Issue by nikolaskyr** [peplin/pygatt#283]
This is more of a question than an issue.  I have been trying to get data from more than two devices but I was only able to do it by having one device connected at a time. Is it possible to take data from more than one device in real time using pygatt?

**Comment by jr3us** [comment]
Have you attempted this yet to see if it would work by creating 2 instances?

**Comment by nikolaskyr** [comment]
No, I didn't end up using pygatt.

**Comment by jr3us** [comment]
What did you use?  I see there is also a pygattlib, that uses their own code  instead of gatttool.

**Comment by nikolaskyr** [comment]
I used bluepy.

**Comment by peplin** [comment]
Only the BGAPI backend supports connecting to more than one device at a time.
