### ISSUE TITLE
Read sensor data from BLE temperature sensor

### ISSUE THREAD

**Issue by jaaanix** [peplin/pygatt#284]
**Question**
Is it possible to do something like this `gatttool -b <my-mac-address> --char-write-req --handle='0x0038' --value="0100" --listen` with pygatt?

**Background**
I have a BLE temperature sensor from mija (LYWSD03MMC).
As mentioned [here](https://github.com/custom-components/sensor.mitemp_bt#supported-sensors) the sensor has some sort of encryption.
Using _gattool_ I am able to read the desired data like temperature and humidity from the sensor, but I can't get it work with _pygatt_.
I think one problem is, that I can't establish a normal bluetooth connection to the device.

**Comment by peplin** [comment]
The encryption mentioned in the docs for that device looks like it's of the actual data returned in a BLE read. If I'm understanding correctly, it should not have any impact on the BLE connection setup or requests themselves. 

If you're still having issues, please let me know more about what's not working with pygatt. There are a few examples in the README of how to subscribe to a device: https://github.com/peplin/pygatt#example-use
