### ISSUE TITLE
pygatt and curses

### ISSUE THREAD

**Issue by egakupi** [peplin/pygatt#288]
I have issues with pygatt and TTY-aware application. 

pygatt uses pexpect: it has some problems with curses app.

I found [ptyprocess](https://github.com/pexpect/ptyprocess). May be It can help, but it has no 1to1 interface with pexpect.

May there are another possible ways to solve the problem

Thanks!

**Comment by peplin** [comment]
Interesting idea! Since `pexpect` is only used by the `gatttool` backend, and `gatttool` itself is deprecated, I'm going to leave it as-is.
