### ISSUE TITLE
Does char_write/char_read for gattool backend correctly handle long writes/reads?

### ISSUE THREAD

**Issue by chris1seto** [peplin/pygatt#293]
I don't see anything in the documentation about this, but I have noticed that simply using char_write does correctly perform a long write. The only trouble is that at the very end, I get the following exception thrown:

`  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/chris/.local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/home/chris/.local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
`

It strikes me as suspicious that this works correctly, for a long write, but there is no documentation about this being supported, and it seems like it doesn't terminate completely correct. It seems like long writes/reads are supported, but calling read/write_char_long for the gattool backend results in a NotImplemented exception. 

Any ideas?

**Comment by peplin** [comment]
Long writes are supported only by the BGAPI backend. I'll mention this in the docs - thanks for flagging it.
