### ISSUE TITLE
Bluegiga chip reset cause issue in VM environment

### ISSUE THREAD

**Issue by paulianttila** [peplin/pygatt#298]
I run ubuntu virtual machine in Proxmox environment. By default, chip reset is done when BGAPIBackend adapter is started.  Reset cause that usb device is unattached and reattached from/to VM and  0,5 second delay after reset, doesn't seems to be enough (serial port open fails).

https://github.com/peplin/pygatt/blob/ab24980d84e3d7043802e3ff27d1bd7412a584cc/pygatt/backends/bgapi/bgapi.py#L209-L220

It took me a while to understand the problem. It works fine is reset is not done or if I increase the timeout. 

Maybe sleep after reset could be configurable from API?

**Comment by peplin** [comment]
Thanks for the report. I think making it configurable sounds good - I'll land a PR for that shortly.
