### ISSUE TITLE
Any way to get signal strength?

### ISSUE THREAD

**Issue by JJack27** [peplin/pygatt#302]

**Comment by peplin** [comment]
Yes, check out the `BLEDevice.get_rssi()` method.

**Comment by jmuellers** [comment]
Apologies for my duplicate question,
I find this raises NotImplementedError(), has the functionality been removed?

**Comment by peplin** [comment]
Only the BGAPI backend implements the get_rssi method: https://github.com/peplin/pygatt/blob/master/pygatt/backends/bgapi/device.py#L56

**Comment by jmuellers** [comment]
> Only the BGAPI backend implements the get_rssi method: https://github.com/peplin/pygatt/blob/master/pygatt/backends/bgapi/device.py#L56

Thanks, I appreciate the feedback
