### ISSUE TITLE
How to send indication ACK

### ISSUE THREAD

**Issue by Gabriel28111989** [peplin/pygatt#305]
Hi,
I am currently working on a BLE Project, where I want to send out data from my peripheral device to a central device via indication.
The reason I'm using indication is, that I want to see an ACK in my application on the peripheral.
Now I have already setup the peripheral to send out indications periodically, and I can receive these via CB in my PyGatt Central. Only I have no clue on how to send back the ACK. 
Any hint would be very appreciated!

**Comment by peplin** [comment]
My memory may be failing me, but I don't think you need to do anything at the user level to send an ACK for an indication. This is handled at a lower level by the BLE driver stack.
