### ISSUE TITLE
How to subscribe to characteristic of multiple slaves at the same time?

### ISSUE THREAD

**Issue by sd1026** [peplin/pygatt#333]
I am able to connect 5 of my BLE slaves to a single master, that is BLED112 dongle. But the problem is that I am unware of how and when to subscribe to their notifications.

All BLE devices are having same services and chracteristics, and I only need one of those characteristics to be subscribed for all slaves and i should receive the data in my application.

I am using pygatt to connect with multiple devices. If its possible then please assist me.

**Comment by YuanjenHung** [comment]
https://github.com/peplin/pygatt/blob/c650b8e805c8216ba9976323136301f8ab251675/pygatt/backends/gatttool/device.py#L24
