### ISSUE TITLE
pip install broken

### ISSUE THREAD

**Issue by IlyaSukhanov** [peplin/pygatt#36]
Upon installing pygatt via pip yields in broken package. Import fails with following error:
> &gt;&gt;&gt; import pygatt.backends
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/user.virtualenvs/pexpect3_test/lib/python3.4/site-packages/pygatt/__init__.py", line 3, in > <module>
>    from .backends import BGAPIBackend, GATTToolBackend  # noqa
> ImportError: No module named 'pygatt.backends'

Appears that pygatt.backends is not part of pip distribution. Missing from setup.py perhaps?

pip install -e . against source works without problems.

**Comment by IlyaSukhanov** [comment]
opened PR with fix https://github.com/peplin/pygatt/pull/38 before which ```python setup.py sdist``` would generate egg without pygatt-2.0.0/pygatt/backends after, with.

**Comment by IlyaSukhanov** [comment]
Christopher do you have access to upload this change to https://pypi.python.org/pypi ? It's somewhat unfortunate that one cannot fetch working version of pygatt from there.

**Comment by peplin** [comment]
Yes, I do, I'm planning to get that taken care of soon.

**Comment by peplin** [comment]
v2.0.1 released to PyPI, sorry for the delay!

```
>>> import pygatt.backends
>>> 
```
