### ISSUE TITLE
Document how to initialize and start the backend

### ISSUE THREAD

**Issue by peplin** [peplin/pygatt#39]
In #37, @IlyaSukhanov mentioned that this backend has a `start()` method that has to be called before it can be used, but that isn't mentioned anywhere.

**Comment by peplin** [comment]
Actually my first comment here was incorrect - the BGAPI *does* have a start method and the docstring does say:

```
Initialize the backend, but don't start the USB connection yet. Must     
        call .start().    
```

so I think my intent was to separate initialization and actually starting, but I forgot to mention this in the docs. I'll update the title.

**Comment by keptenkurk** [comment]
And maybe add a link to [this blog](http://flowcloud.github.io/ci20-bluetooth-LE/2015/09/10/bluetooth-control-in-python/) which explains the pygatt workings at newbee level.
