### ISSUE TITLE
gatttool high CPU usage on 'disconnect' command

### ISSUE THREAD

**Issue by gkopendev** [peplin/pygatt#46]
Hi,
This is not exactly a pygatt issue, but I just wanted to get some inputs. Doing a gatttool disconnect causes CPU usage of 70-80% till gatttool is killed. I am using bluez 5.37. I also notice this issue has been noted as a TODO in gatttool.py. So has anyone had a go at trying to resolve this?

Thanks

**Comment by gkopendev** [comment]
If anyone looks for this I describe the solution here - 
https://communities.intel.com/thread/100451
http://stackoverflow.com/questions/36289272/gatttool-disconnection-in-bluez-5-3-causes-very-high-cpu-usage-linux-bluetooth/36310040#36310040

**Comment by peplin** [comment]
I am not seeing this issue anymore - it may have been fixed upstream.
