### ISSUE TITLE
Unable to auto-detect BLED112 serial port

### ISSUE THREAD

**Issue by amahlaka** [peplin/pygatt#49]
Hi, im trying to use pygatt on raspi, when i run ``` adapter = pygatt.backends.BGAPIBackend() ``` i get 
``` Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pygatt/backends/bgapi/bgapi.py", line 79, in __init__
    raise BGAPIError("Unable to auto-detect BLED112 serial port") ```
what does this mean?
i have a usb bluetooth 4 le dongle connected
im running python as sudo

**Comment by amahlaka** [comment]
Fixed using ```  adapter = pygatt.backends.GATTToolBackend() ```

**Comment by peplin** [comment]
Really? I'm surprised by that - the BLED112 doesn't work with gatttool/BlueZ as far as I know.

**Comment by weilonluo** [comment]
> Fixed using adapter = pygatt.backends.GATTToolBackend()
BLEError: The GATTToolBackend requires BlueZ, which is not available in Windows

**Comment by goodtalen** [comment]
self.adapter = pygatt.backends.GATTToolBackend()

   raise BLEError("The GATTToolBackend requires BlueZ, "
pygatt.exceptions.BLEError: The GATTToolBackend requires BlueZ, which is not available in Windows

**Comment by amahlaka** [comment]
As the error says, blueZ is not available in windows

**Comment by ErfolgreichCharismatisch** [comment]
so pygatt cannot be used under windows at all?

**Comment by chadkennedyonline** [comment]
Under Windows, pygatt works great, using the BLED112 adapter, along with the BGAPI backend.

**Comment by ErfolgreichCharismatisch** [comment]
I don't have the bled112 adapter. How do I use it under Windows?

**Comment by chadkennedyonline** [comment]
As far as I know, you don't. You'd have to buy a BLED112. I checked and they're available on mouser.de for 19,77 €: https://www.mouser.de/ProductDetail/Silicon-Labs/BLED112-V1?qs=2bnkQPT%252BPaf%252BBQ6Sw8mJqQ%3D%3D
