### ISSUE TITLE
pip install pygatt[GATTTOOL] -> Error: no matches found: pygatt[GATTTOOL]

### ISSUE THREAD

**Issue by BenRoe** [peplin/pygatt#63]
If i use the install command from the README on Debian
`pip install pygatt[GATTTOOL]`
i get the following error

> no matches found: pygatt[GATTTOOL]

I found the solution. Put quote around pygatt. 
`pip install 'pygatt[GATTTOOL]'`

**Comment by peplin** [comment]
Thanks - I think this depends on which shell you are using. For example, it works OK in bash - are you using something like zsh or an alternative?

Regardless, I'll update the docs to recommend quotes since they can't hurt!
