### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by Alionea** [peplin/pygatt#69]
Hello,

i use a new Raspberry pi3 with the newest Version of Raspbian. I followed every instruction to install Bluez, Gatttool and pygatt.  I have no Idea how to manage this Error. Please can you help me.
The  Error is:

Traceback (most recent call last):
  File "/home/pi/MIA/char_read.py", line 13, in <module>
    device = adapter.connect("D6:2C:B6:38:DF:24", address_type=ADDRESS_TYPE)
  File "/usr/local/lib/python2.7/dist-packages/pygatt/backends/gatttool/gatttool.py", line 319, in connect
    cmd = 'connect {0} {1}'.format(self._address, address_type.name)
AttributeError: 'str' object has no attribute 'name'

Thank you!

**Comment by Alionea** [comment]
Ok i found the Error- writing only

device = adapter.connect("D6:2C:B6:38:DF:24") 

but why? I have the same skript running on a different image (instatlled jessy lite)- and there it works fine...

**Comment by peplin** [comment]
Does your device use public or random addressing? The `connect` function requires an `pygatt.BLEAddressType` be passed in to the `address_type` argument - from the first error you posted, it looks like you are trying to pass a string. This changed recently with the latest version of Pygatt, which probably explains why the script only fails on the new board (see the [CHANGELOG](https://github.com/peplin/pygatt/blob/master/CHANGELOG.mkd) for details).

If you do need random addressing, change your script to say:

```
ADDRESS_TYPE = pygatt.BLEAddressType.random
device = adapter.connect("D6:2C:B6:38:DF:24", address_type=ADDRESS_TYPE)
```

(see the [updated example](https://github.com/peplin/pygatt/blob/master/samples/basic_bluez_gatttool_sample.py))

Please re-open if that doesn't fix your issue!
